Update add-user list

diff --git a/add-user b/add-user
--- a/add-user
+++ b/add-user
@@ -1,29 +1,82 @@
-if [ $(id -u) -eq 0 ]; then
-	read -p "Enter username : " username
-	 egrep "^$username" /etc/passwd >/dev/null
-	  if [ $? -eq 0 ]; then
-		echo -e "user $username exists!"
-		exit 1
-	  fi
-	read -p "Enter expire date ( y-m-d ) example 2023-06-10 : " date
-	read -p "Enter traffic (GB) : " traffic  
-	read -p "Enter password : " password
-		pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
-		useradd -m -p "$pass" "$username" --shell=/bin/false
-		usermod -e  "$date" "$username"
-	
-		prefix=1000000000
-	        gb=$((traffic * prefix))
-		iptables -A OUTPUT -p tcp -m owner --uid-owner $username -m quota --quota $gb -j ACCEPT
-		[ $? -eq 0 ] &&  echo -e "user added :) "
-    echo -e "----------------------------------------------"
-    echo -e "username : "$username
-    echo -e "expiry date : "$date
-    echo -e "traffic (GB) : "$traffic
-    echo -e "password : "$password
-    echo -e "----------------------------------------------" || echo "Failed to add a user!"
+#!/bin/bash
+
+# تابع برای اضافه کردن کاربر
+add_user() {
+    read -p "Enter username : " username
+    egrep "^$username" /etc/passwd >/dev/null
+    if [ $? -eq 0 ]; then
+        echo -e "user $username exists!"
+        exit 1
+    fi
+
+    read -p "Enter expire date ( y-m-d ) example 2023-06-10 : " date
+    read -p "Enter traffic (GB) : " traffic  
+    read -p "Enter password : " password
+    pass=$(perl -e 'print crypt($ARGV[0], "password")' $password)
+    useradd -m -p "$pass" "$username" --shell=/bin/false
+    usermod -e  "$date" "$username"
     
+    prefix=1000000000
+    gb=$((traffic * prefix))
+    iptables -A OUTPUT -p tcp -m owner --uid-owner $username -m quota --quota $gb -j ACCEPT
+    
+    if [ $? -eq 0 ]; then
+        echo -e "user added :) "
+        echo -e "----------------------------------------------"
+        echo -e "username : $username"
+        echo -e "expiry date : $date"
+        echo -e "traffic (GB) : $traffic"
+        echo -e "password : $password"
+        echo -e "----------------------------------------------"
+    else
+        echo "Failed to add a user!"
+    fi
+}
+
+# تابع برای نمایش کاربران
+show_users() {
+    echo "Current users:"
+    cut -d: -f1 /etc/passwd
+}
+
+# تابع برای حذف کاربر
+delete_user() {
+    read -p "Enter username to delete: " username
+    userdel -r "$username"
+    if [ $? -eq 0 ]; then
+        echo "User $username has been deleted."
+    else
+        echo "Failed to delete user $username."
+    fi
+}
+
+# چک کردن اینکه آیا کاربر روت است
+if [ $(id -u) -eq 0 ]; then
+    PS3='Please select an option: '  # تنظیم پیام منو
+    options=("Add User" "Show Users" "Delete User" "Quit")
+    
+    select opt in "${options[@]}"
+    do
+        case $opt in
+            "Add User")
+                add_user
+                ;;
+            "Show Users")
+                show_users
+                ;;
+            "Delete User")
+                delete_user
+                ;;
+            "Quit")
+                echo "Exiting the script."
+                break
+                ;;
+            *)
+                echo "Invalid option. Please try again."
+                ;;
+        esac
+    done
 else
-	echo "Only root may add a user to the system."
-	exit 2
+    echo "Only root may add a user to the system."
+    exit 2
 fi
